app:
  name: "nasdaq-itch-order-book"
  environment: "development"
  debug: true

database:
  host: "localhost"
  port: 5432
  user: "postgres_admin"
  # Reference the env variable dynamically
  password: !env DB_PASSWORD 

services:
  weather_api:
    url: "https://weather.com"
    timeout: 30
    token: !env API_TOKEN
  databento:
    client_library: "databento"
    base_url: "https://hist.databento.com/v0"